version: '3.8'
services:
  django:
    build: .
    command: gunicorn dockercicd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - ./dockercicd/.env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
    networks:
      - app-network
  
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: cicd_database
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: