# Generated by Django 5.1 on 2024-08-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dockercicdapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
    ]
